// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp1.Data;

#nullable disable

namespace MyApp1.Migrations
{
    [DbContext(typeof(MyApp1Context))]
    [Migration("20260610185421_OnModelCeating category")]
    partial class OnModelCeatingcategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp1.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            id = 2,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("MyApp1.Models.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("IdSerial")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IdSerial")
                        .IsUnique()
                        .HasFilter("[IdSerial] IS NOT NULL");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            IdSerial = 10,
                            Name = "Microphone",
                            Price = 40.0
                        });
                });

            modelBuilder.Entity("MyApp1.Models.Persone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("date")
                        .HasColumnName("dataNascita");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Persone");
                });

            modelBuilder.Entity("MyApp1.Models.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SerialNumber");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "MIC150"
                        });
                });

            modelBuilder.Entity("MyApp1.Models.Items", b =>
                {
                    b.HasOne("MyApp1.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.HasOne("MyApp1.Models.SerialNumber", "SerNumber")
                        .WithOne("Item")
                        .HasForeignKey("MyApp1.Models.Items", "IdSerial");

                    b.Navigation("Category");

                    b.Navigation("SerNumber");
                });

            modelBuilder.Entity("MyApp1.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyApp1.Models.SerialNumber", b =>
                {
                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
